ProjectDoc/Controllers/HomeController.cs
using ProjectDoc.DAL;
using ProjectDoc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectDoc.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            Session["ID"] = null;
            Session["userName"] = null;
            Session["campID"] = null;
            Session["admin"] = null;
    
            return View();
        }

        public ActionResult MainPage(Player p)
        {
            if (p!=null)
                return View(p);
            return HttpNotFound();
        } 
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Profile()
        {
            ViewBag.Message = "Your Profile";
            return View();
        }
        public ActionResult Explore()
        {
            ViewBag.Message = "Find DOC";
            return View();
        }

        public ActionResult campPage()
        {
            ViewBag.Message = "Camp Page";
            return View();
        }
    }
}

ProjectDoc/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectDoc.DAL;
using ProjectDoc.Models;

namespace ProjectDoc.Controllers
{
    public class PlayerController : Controller
    {
        private DataContext db = new DataContext();
        

        // GET: Player
        public ActionResult Index()
        {
            return View(db.Players.ToList());
        }

        // GET: Player/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // GET: Player/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserName,Password,Team,Position,GoalsSum,AssistsSum,InterceptionsSum")] Player player)
        {
            if (ModelState.IsValid)
            {
                if(player.Age<10 || player.Age>35 || db.Players.Any(p=>p.UserName==player.UserName))
                {
                    return View(player);
                }
                db.Players.Add(player);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(player);
        }

        // GET: Player/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Player/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,Password,Team,Position,Goals,Assists,Interceptions")] Player player)
        {
            if (ModelState.IsValid)
            {
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Player/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Player player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

  
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            Player p = new Player();
            return View(p);
        }

        [HttpPost]
        public ActionResult AddOrEdit(Player p)
        {
                if (db.Players.Any(m => m.UserName == p.UserName) || p.Age < 10 || p.Age > 35)
            {
                ViewBag.DuplicateMessage = "User Name Already Taken!";
                return RedirectToAction("Index","Home");
            }
            else
            {
                db.Players.Add(p);
                db.SaveChanges();
                ModelState.Clear();
                Session["userName"] = p.UserName;
                Session["ID"] = p.ID.ToString();
                ViewBag.SuccessMessage = Session["userName"];
            }

            return View("Profile", p);
        }

        [HttpGet]
        public ActionResult Login(int id = 0)
        {
            Player p = new Player();

            return View(p);
        }
        [HttpPost]
        public ActionResult Login(Player p)
        {
            if (db.Players.Any(m => m.UserName == p.UserName && m.Password == p.Password))
            {
                Session["userName"] = p.UserName;
                Session["ID"] = p.ID;
                ViewBag.Logged = "Hello " + Session["userName"];
                Player player = db.Players.Where(m => m.UserName == p.UserName).Where(m=> m.Password == p.Password).First();
                return View("Profile",player);
            }

            Session["userName"] = null;
            ViewBag.Message = "Log-In Failed";
            return RedirectToAction("Index","Home");
        }

        public ActionResult Profile(Player p)
        {
            Player player = new Player();

            var pls = db.Players.ToArray();
            for (var i = 0;i <pls.Length;i++)
            {
                if (pls[i].UserName.Equals(Session["userName"].ToString()))
                {
                    player = pls[i];
                    player.updateStats();
                    db.Entry(player).State = EntityState.Modified;
                    db.SaveChanges();
                    pls =pls.OrderBy(pyr => pyr.GoalsSum).ToArray();
                    if (pls.Last().UserName == player.UserName)
                        player.ficici = true;
                    pls = pls.OrderBy(pyr => pyr.AssistsSum).ToArray();
                    if (pls.Last().UserName == player.UserName)
                        player.topChef = true;
                    pls = pls.OrderBy(pyr => pyr.InterceptionsSum).ToArray();
                    if (pls.Last().UserName == player.UserName)
                        player.lastStop= true;
                    
                    return View(player);
                }
            }
            

            return RedirectToAction("Index", "Home");
        }

        public ActionResult About()
        {
            return View();
        }
        /*public ActionResult Profile()
        {
            var id = Session["ID"];
            Player p = db.Players.Find(id);
            if(p !=null)
            {
                return View(p);
            }
            else
            {
                ViewBag.Message = "User Not Logged In";
                return RedirectToAction("Index","Home");
            }
            
        }*/

        public ActionResult LogOut()
        {
            Session["userName"] = null;
            Session["ID"] = null;
            ViewBag.Message = "User Logged Out!";
            return RedirectToAction("Index", "Home");

        }



        public ActionResult Explore()
        {
            return View();
        }



        /*
         * Landing Page ->
         * Log In / Register -->
         * OR --> bad access return to this page 
         * OR --> good access redirect to profile page
         * Profile Page --->
         * OR --> Find DOC page
         * OR --> View personal stats / camps 
         * OR --> About
         * OR --> Log out Btn --> return to Log in / Register
         */
    }
}

ProjectDoc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    <link rel="stylesheet" type="text/css" href="~/Content/aboutStyle.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
}


<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img id="firstImg" src="http://www.stubhubcenter.com/assets/img/Training-Field-7-b6561416a0.JPG" >
                <div class="carousel-caption">
                    <h3>
                        DOC - Daniel & Ofir Community
                    </h3>
                    <p id="firstPara">
                          It's a place for young and talented players to find the best training camps that would help them get better and become pro's!
                    </p>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">
                <img id="secondImg" src="http://www.rubbuk.com/images/sports/projects/sunderland/sunderland1_large.jpg">
                <div class="carousel-caption">
                    <h3>
                        DOC - Facilities
                    </h3>
                    <p id="secondPara">
                        We provide 5 Facilities all around the glob with top-class coaches and verius of different camps for all kinds of players! 
                    </p>
                </div>
            </div>
            <!-- End Item -->

            <div class="item">
                <img src="http://placehold.it/1200x400/2980b9/ffffff&text=Portfolio">
                <div class="carousel-caption">
                    <h3>
                        Ofir Kariv
                    </h3>
                    <p id="ofirDetails">
                        Email: hakeeee@gmail.com <br />
                        Linkdin: <br />
                        Facebook: <br />
                        Tinder:<br />
</div>
            </div>
            <!-- End Item -->
            <div class="item">
                <img id="forthImg" src="https://scontent.ftlv1-1.fna.fbcdn.net/v/t31.0-8/20616025_10213778587161778_5477492581956885505_o.jpg?oh=17923ee337ceb3b17420aa0ec84d904e&oe=5A76E1B9">
                <div class="carousel-caption">
                    <h3>
                        Daniel Hake
                    </h3>
                    <p id="danielDetails">
                    Email: hakeeee@gmail.com <br />
                    Linkdin: <br />
                    Facebook: <br />
                    Tinder:<br />
                    </p>
                </div>
            </div>
            <!-- End Item -->
        </div>
        <!-- End Carousel Inner -->
        <ul class="nav nav-pills nav-justified">
            <li data-target="#myCarousel" data-slide-to="0" class="active">
                <a href="#">
                    DOC <small>
                        what are we
                    </small>
                </a>
            </li>
            <li data-target="#myCarousel" data-slide-to="1">
                <a href="#">
                    DOC<small>
                       how it's going to work
                    </small>
                </a>
            </li>
            <li data-target="#myCarousel" data-slide-to="2">
                <a href="#">
                    Ofir Kariv<small>
                        AKA - Lightning buzz
                    </small>
                </a>
            </li>
            <li data-target="#myCarousel" data-slide-to="3">
                <a href="#">
                    Daniel Hake<small>
                        AKA - The Man
                    </small>
                </a>
            </li>
        </ul>
    </div>
    <!-- End Carousel -->
</div>

@Scripts.Render("https://code.jquery.com/jquery-3.2.1.js")
@Scripts.Render("~/Scripts/aboutFunc.js")

ProjectDoc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjectDoc/Views/Home/Index.cshtml
@model ProjectDoc.Models.Player

@{
    ViewBag.Title = "Home Page";
        <link rel="stylesheet" type="text/css" href="~/Content/homeIndexStyle.css">
    Layout = "~/Views/Shared/_Layout.cshtml";


}
<!--
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
-->

<div>
    <img src="https://thefootballartist.files.wordpress.com/2015/05/w5.jpg?w=545" id="welcomeImg">
    <aside><h1 id="welcomeMsg"> Welcome To DO Community </h1></aside>
</div>

<div class="container" id="loginArea">
    <div class="row" id="firstRow">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Login</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Register</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="loginForm">
                                @using (Html.BeginForm("Login", "Player", FormMethod.Post))
                                {
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @type = "text", @name = "username", @id = "username", @tabindex = "1", @class="form-control", @placeholder="Username", @value="" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">-->
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type = "password", @name = "password" ,@id = "password", @tabindex = "2", @class="form-control", @placeholder="Password",@value="" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    <!--<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">-->
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-lg-12">
                                        </div>
                                    </div>
                                </div>
                                }
                            </div>                            
                            <div id="regiForm">
                            @using (Html.BeginForm("AddOrEdit", "Player", FormMethod.Post))
                            {
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @type = "text", @name = "username", @id = "username", @tabindex = "1", @class = "form-control", @placeholder = "Username", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">-->
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type = "password", @name = "password", @id = "password", @tabindex = "2", @class = "form-control", @placeholder = "Password", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    <!--<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">-->
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @type = "password", @name = "confirmpassword", @id = "confirmpassword", @tabindex = "2", @class = "form-control", @value = "", @placeholder = "Confirm Password" } })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="team" id="team" tabindex="1" class="form-control" placeholder="Team" value="">-->
                                </div>

                                <div class="form-group">
                                    @Html.EditorFor(model => model.Team, new { htmlAttributes = new { @type = "text", @name = "team", @id = "team", @tabindex = "1", @class = "form-control", @placeholder = "Team", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="team" id="team" tabindex="1" class="form-control" placeholder="Team" value="">-->
                                </div>
                                <div class="form-group">
                                 @Html.DropDownListFor(model => model.Position, new SelectList(Enum.GetValues(typeof(ProjectDoc.Models.Positions))), "Select Position", new { @class = "form-control", @value = "" })
                                   <!-- Html.EditorFor(model => model.Position, new { htmlAttributes = new { type = "text", name = "position", id = "position", tabindex = "1", class = "form-control", placeholder = "Position Playing",value = "" } })-->
                                    @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="position" id="position" tabindex="1" class="form-control" placeholder="Position Playing" value="">-->
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @type = "slide", @max = "25", @min = "10", @name = "age", @id = "age", @tabindex = "1", @class = "form-control", @placeholder = "Age", @value = "" } })
                                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                                    <!--<input type="text" name="age" id="age" tabindex="1" class="form-control" placeholder="Age" value="">-->
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                                        </div>
                                    </div>
                                </div>
                            }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<h1>@ViewBag.Message</h1>



@Scripts.Render("https://code.jquery.com/jquery-3.2.1.js")
@Scripts.Render("~/Scripts/layout.js")

ProjectDoc/Views/Home/MainPage.cshtml
@{
    ViewBag.Title = "Home Page";
        <link rel="stylesheet" type="text/css" href="~/Content/homeIndexStyle.css">
    Layout = "~/Views/Shared/layout1.cshtml";
}

<!--
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
-->

<div>
    <img src="https://thefootballartist.files.wordpress.com/2015/05/w5.jpg?w=545" id="welcomeImg">
    <h1 id="welcomeMsg"> Welcome To DO Community </h1>
</div>

<video width="320" height="240" id="video"  controls>
    <source src="~/Lib/Nike commercial The Mission (No! Its rounder!) wide screen no black bars.mp4" type="video/mp4">
    <source src="~/Lib/Nike commercial The Mission (No! Its rounder!) wide screen no black bars.ogg" type="video/ogg">
    Your browser does not support the video tag.
</video>

@Scripts.Render("https://code.jquery.com/jquery-3.2.1.js")
@Scripts.Render("~/Scripts/layout.js")