ProjectDoc/Models/Camp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectDoc.Models

{
    public class Camp
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int NumOfPlayers { get; set; }

        public DateTime sDate { get; set; }
        public DateTime eDate { get; set; }

        public Locations? Location { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Player> Players { get; set; }

        public void AddPlayerToList(Player Player)
        {
            Players.Add(Player);
        }
        public void AddCommentrToList(Comment Comment)
        {

            Comments.Add(Comment);
        }

        public bool isFinished()
        {            
            DateTime now = DateTime.Now;
 
            return (eDate<now);
        }


        public int AvailablePlaces()
        {
            int SeatsTaken;


            if (Players == null)
            {

                SeatsTaken = 0;
                return 0;
            }
            else
                SeatsTaken = Players.Count();



            return NumOfPlayers - SeatsTaken;
        }

        public int Registered()
        {
            if (Players == null)
                return 0;
            return Players.Count();
                
        }

        public int NumOfComments()
        {

            if (Comments == null)
                return 0;
            else
                return Comments.Count();


        }


    }
    public enum Locations
    {
        Turin,
        Barcelona,
        London,
        Jerusalem

    }
}

ProjectDoc/Controllers/CampController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectDoc.DAL;
using ProjectDoc.Models;

namespace ProjectDoc.Controllers
{
    public class CampController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Camp
        public ActionResult Index()
        {
            return View(db.Camps.ToList());
        }

        public ActionResult Explore()
        {
            return View(db.Camps.ToList());
        }

        [HttpPost]
        public ActionResult Explore(string titleSearch, string descSearch, string locationSearch,string firstPlayerSearch, string secondPlayerSearch)
        {
            
            IEnumerable<Camp> camps = from m in db.Camps select m;
            if(!String.IsNullOrEmpty(locationSearch) && !String.IsNullOrEmpty(descSearch) && !String.IsNullOrEmpty(descSearch) && !String.IsNullOrEmpty(titleSearch) && !String.IsNullOrEmpty(firstPlayerSearch) && !String.IsNullOrEmpty(secondPlayerSearch))
            {
                camps = camps.Where(a=>a.Location.ToString()=="Telaviv").ToList();
            }
            if (!String.IsNullOrEmpty(locationSearch))
            {
                var cmp = camps.GroupBy(a => a.Location);
                foreach (var a in cmp)
                {
                    if (a.Key.ToString() == locationSearch)
                    {
                        camps = a.Select(aa => aa).Where(b => b.Location.ToString() == locationSearch).ToList();
                    }
                }
            }

            if (!String.IsNullOrEmpty(descSearch))
            {
                camps = camps.Where(d => d.Description.Contains(descSearch));
            }
     
            if (!String.IsNullOrEmpty(titleSearch))
            { 
                
                camps = camps.Where(t => t.Name == titleSearch);
            }
     
            if (!String.IsNullOrEmpty(firstPlayerSearch))
            {
                camps = camps.Where(c=>c.Players.Any(a=>a.UserName==firstPlayerSearch));
            }

            if (!String.IsNullOrEmpty(secondPlayerSearch))
            {
                camps = camps.Where(c => c.Players.Any(a => a.UserName == secondPlayerSearch));
            }
                return View(camps);
        }


        // GET: Camp/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camp camp = db.Camps.Find(id);
            if (camp == null)
            {
                return HttpNotFound();
            }

            Session["campID"] = camp.ID;
            return View(camp);
        }

        // GET: Camp/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Camp/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,NumOfPlayers,sDate,eDate,Location")] Camp camp)
        {
            if (ModelState.IsValid)
            {
                if ((camp.sDate.CompareTo(camp.eDate) < 0)){
                    db.Camps.Add(camp);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(camp);
        }

        // GET: Camp/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camp camp = db.Camps.Find(id);
            if (camp == null)
            {
                return HttpNotFound();
            }
            Session["campID"] = camp.ID;
            return View(camp);
        }

        // POST: Camp/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,NumOfPlayers,sDate,eDate,Location")] Camp camp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(camp).State = EntityState.Modified;
                db.SaveChanges();
                Session["campID"] = camp.ID;
                return RedirectToAction("Index");
            }
            return View(camp);
        }

        // GET: Camp/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camp camp = db.Camps.Find(id);
            if (camp == null)
            {
                return HttpNotFound();
            }
            Session["campID"] = camp.ID;
            return View(camp);
        }

        // POST: Camp/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Camp camp = db.Camps.Find(id);
            db.Camps.Remove(camp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult CampPage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Camp camp = db.Camps.Find(id);
            if (camp == null)
            {
                return HttpNotFound();
            }

            Session["campID"] = camp.ID;
            return View(camp);

        }


        /*  public ActionResult RegisterPlayer(int? id)
          {
              if (String.IsNullOrEmpty(Session["ID"].ToString()))
              {
                  return RedirectToAction("Index", "Home");
              }
              string playerid = Session["ID"].ToString();

              Player player = null;
              var pls = db.Players.ToArray();
              for (var i = 0;i<pls.Length;i++)
              {
                  if (Session["userName"].ToString().Equals(pls[i].UserName))
                      player = pls[i];
              }

              if (id == null)
              {
                  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
              }
              Camp camp = db.Camps.Find(id);
              if (camp == null)
                  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);           
              if (player == null)
                  return HttpNotFound();

              int Available = camp.AvailablePlaces();
              bool canRegisterCamp = true;
              if (camp.Players == null)
              {
                  camp.Players = new List<Player>();
              }

                  pls = camp.Players.ToArray();
              for (var j=0;j<pls.Length;j++)
              {
                  if (pls[j].UserName.Equals(player.UserName))
                      canRegisterCamp = false;
              }
             // canRegisterCamp = player.isFreeDate(camp);
           //   canRegisterCamp = player.isExists(camp);


              if (Available > 0 && canRegisterCamp)
              {
                  if (camp.Players == null)
                      camp.Players = new List<Player>();

                  if (player.Camps == null)
                      player.Camps = new List<Camp>();

                  player.Camps.Add(camp);
                  camp.Players.Add(player);


                  db.Entry(camp).State = EntityState.Modified;
                  db.Entry(player).State = EntityState.Modified;
                  db.SaveChanges();
              }


              return RedirectToAction("campPage", camp);

          }

      */
        public ActionResult RegisterPlayer(int? id)
        {
            if (String.IsNullOrEmpty(Session["ID"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }

            Player player = null;
            var pls = db.Players.ToArray();
            for (var i = 0; i < pls.Length; i++)
            {
                if (Session["userName"].ToString().Equals(pls[i].UserName))
                    player = pls[i];
            }

            /*if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
            Camp camp = db.Camps.Find(id);
            if (camp == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (player == null)
                return HttpNotFound();

            int Available = camp.AvailablePlaces();
            //    bool canRegisterCamp = true;
            /*     if (camp.Players == null)
                 {
                     camp.Players = new List<Player>();
                 }

                 pls = camp.Players.ToArray();
                 for (var j = 0; j < pls.Length; j++)
                 {
                     if (pls[j].UserName.Equals(player.UserName))
                         canRegisterCamp = false;
                 }*/
            // canRegisterCamp = player.isFreeDate(camp);
            //  canRegisterCamp = player.isExists(camp);


            if (Available > 0 && player.isFreeDate(camp) && player.isExists(camp))
            {
                if (camp.Players == null)
                    camp.Players = new List<Player>();

ProjectDoc/Controllers/StatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectDoc.DAL;
using ProjectDoc.Models;

namespace ProjectDoc.Controllers
{
    public class StatsController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Stats
        public ActionResult Index()
        {
            return View(db.Stats.ToList());
        }

        // GET: Stats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stats stats = db.Stats.Find(id);
            if (stats == null)
            {
                return HttpNotFound();
            }
            return View(stats);
        }

        // GET: Stats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CampID,PlayerID,PlayerGoals,PlayerAssists,PlayerInter")] Stats stats)
        {
            if (ModelState.IsValid)
            {
                db.Stats.Add(stats);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stats);
        }

        // GET: Stats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stats stats = db.Stats.Find(id);
            if (stats == null)
            {
                return HttpNotFound();
            }
            return View(stats);
        }

        // POST: Stats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CampID,PlayerID,PlayerGoals,PlayerAssists,PlayerInter")] Stats stats)
        {
            if (ModelState.IsValid)
            {
                if(stats.PlayerAssists<0 || stats.PlayerInter < 0 || stats.PlayerGoals < 0)
                {
                    return View(stats);
                }
                db.Entry(stats).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stats);
        }

        // GET: Stats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stats stats = db.Stats.Find(id);
            if (stats == null)
            {
                return HttpNotFound();
            }
            return View(stats);
        }

        // POST: Stats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stats stats = db.Stats.Find(id);
            db.Stats.Remove(stats);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectDoc/Views/Camp/CampPage.cshtml
@model ProjectDoc.Models.Camp
@{
    ViewBag.Title = "campPage";
    <link rel="stylesheet" type="text/css" href="~/Content/campPageStyle.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    Layout = "~/Views/Shared/layout1.cshtml";

}


<!-- start camp page -->
<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
    <div class="row panel">
        <div class="col-md-offset-4 col-xs-12">
        </div>
        <div id="campHeader" class="col-md-4 col-xs-12">
            <div class="header">
                <h1>@Html.DisplayFor(model => model.Name)</h1>
                <h4 id="loc">@Html.DisplayFor(model => model.Location)</h4>
                <strong>Start Date:</strong>
                <h6>@Html.DisplayFor(model => model.sDate)</h6>
                <strong>End Date:</strong> 
                <h6>@Html.DisplayFor(model => model.eDate)</h6>
                <strong>Description:</strong> 
                <span>@Html.DisplayFor(model => model.Description)</span>
            </div>
        </div>
        <div class="col-md-4 bg_blur">

            <!---- <a href="#" class="follow_btn hidden-xs"></a>-->
            @Html.ActionLink("Register Player", "RegisterPlayer", new { id = Model.ID })
        </div>
        <div class="col-md-4">
            <img id="imgHeader" src="https://i.imgur.com/edlW6yu.jpg" class="img-thumbnail picture" />
            <img id="imgHeader" src="https://i.imgur.com/edlW6yu.jpg" class="img-thumbnail visible-xs picture_mob" />
        </div>
    </div>

    <div class="row nav">
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-weixin fa-lg"></i> Places: <span id="placesSpan">@Html.DisplayFor(model => model.NumOfPlayers)</span></div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-heart-o fa-lg"></i> Registrated: <span id="registeredSpan">@Model.Registered()</span></div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-thumbs-o-up fa-lg"></i> Free Seats:<span id="freSeatsSpan">@Model.AvailablePlaces()</span> </div>
        </div>
    </div>
</div>
<!-- end camp page -->
<!-- start comments  -->


<div class="container" id="commentsArea">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><label class="text-left">@Model.NumOfComments()</label> Comments </h1>
            </div>


            <div class="comments-list">
                @if (Model.Comments != null)
                {
                   foreach (var c in Model.Comments)
                    {
                        
                        <div class="media">
                            <p class="pull-right"><small>@Html.DisplayFor(m => c.CommentDate)</small></p>
                            <a class="media-left" href="#">
                                <img class="icon" src="https://www.shareicon.net/data/128x128/2015/12/03/681786_man_512x512.png">
                            </a>
                            <div class="media-body">

                                <h4 class="media-heading user_name">@Html.DisplayFor(m => c.Writer)</h4>
                                <td>@Html.DisplayFor(m => c.CommentText)</td>

                                
                            </div>
                        </div>
                    }
                }
            </div>
        </div>

        
        @using (Html.BeginForm("CreateComment", "Camp", FormMethod.Post))
        {

            @Html.AntiForgeryToken()
            @Html.TextBox("Text", null, new { @name = "Text", @class = "form-control", @value = "", @id="text",@placeholder = "Your comment:" })
            <button id="addCommentBtn" type="submit" class="btn-group" name="Add">Add Comment</button>
        }
        


    </div>
</div>
<!-- end comments -->



@Scripts.Render("https://code.jquery.com/jquery-3.2.1.js")
@Scripts.Render("~/Scripts/campPageFunc.js")

ProjectDoc/Views/Camp/Delete.cshtml
@model ProjectDoc.Models.Camp

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/layoutAdmin.cshtml";

}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Camp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfPlayers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfPlayers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.eDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectDoc/Views/Camp/Edit.cshtml
@model ProjectDoc.Models.Camp

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/layoutAdmin.cshtml";

}

<h2>Edit Camp Page</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.eDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.eDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.eDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Location, new SelectList(Enum.GetValues(typeof(ProjectDoc.Models.Locations))), "Select Location", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<table class="table table-hover table-striped">
    <tr>
        <td></td>
    <td>Name</td>
        <td>Goals</td>
    <td> Assists</td>
        <td>Intercipetions</td>
        <td></td>
    </tr>
    <tbody>
        @foreach (var i in Model.Players.Where(a=>a.gotCampStat(Model.ID)))
        {
            <tr>
                <td></td>
                
                <td class="mailbox-name">@Html.DisplayFor(name => i.UserName, new { @class = "form-control" })</td>
                <td class="mailbox-attachment goalsTab">@Html.DisplayFor(name => i.Stats.Where(a=>a.CampID ==Model.ID).First().PlayerGoals, new { @class = "form-control" })</td>
                <td class="mailbox-attachment assistsTab"> @Html.DisplayFor(name => i.Stats.Where(a => a.CampID == Model.ID).First().PlayerAssists, new { @class = "form-control" })</td>
                <td class="mailbox-attachment interceptionsTab">@Html.DisplayFor(name => i.Stats.Where(a => a.CampID == Model.ID).First().PlayerInter, new { @class = "form-control" })</td>
                <td class="mailbox-date">@Html.ActionLink("Edit Player Stats", "Edit", "Stats", i, null)</td>
            </tr>
        }
        </tbody>
    </table>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

ProjectDoc/Views/Camp/Explore.cshtml
@model IEnumerable<ProjectDoc.Models.Camp>
@{
    ViewBag.Title = "Explore";
    <link rel="stylesheet" type="text/css" href="~/Content/exploreStyle.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    Layout = "~/Views/Shared/layout1.cshtml";
}
<div class="jumbotron">
    <h2 id"headMsg"> Find & Register To Your Next Camp!</h2>
    <img id="fergiImg" class="img-responsive img-circle" src="~/Lib/alexFerguson.jpg" />

</div>

    @using (Html.BeginForm("Explore", "Camp", FormMethod.Post))
    {
        <div class="container" id="campTable">
            <div id="searchCampForm" class="navbar-form">
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    @Html.TextBox("titleSearch", null, new { @class = "form-control", @id = "titleSearch", @type = "text", @name = "title", @value = "", @placeholder = "Title" })
                </div>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <!--Html.TextBox("locationSearch", null, new { class = "form-control", id = "locationSearch", type = "text", name = "location",value = "", placeholder = "Location" })-->
                    @Html.DropDownList("locationSearch", new SelectList(Enum.GetValues(typeof(ProjectDoc.Models.Locations))),"Select Location" ,new { @class = "form-control", @id = "locationSearch", @type = "text", @name = "location", @value = "", @placeholder = "Location" })
                </div>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    @Html.TextBox("descSearch", null, new { @class = "form-control", @id = "descSearch", @type = "text", @name = "description", @value = "", @placeholder = "Description" })
                </div>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    @Html.TextBox("firstPlayerSearch", null, new { @class = "form-control", @id = "firstPlayerSearch", @type = "text", @name = "firstPlayer", @value = "", @placeholder = "Player1 Participate" })
                </div>
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    @Html.TextBox("secondPlayerSearch", null, new { @class = "form-control", @id = "secondPlayerSearch", @type = "text", @name = "secondPlayer", @value = "", @placeholder = "Player2 Participate" })
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    }
                
        
    <div class="row">
        <div class="box-body no-padding">
            <div class="mailbox-controls">
                <!-- Check all button -->
            </div>
            <hr>
            <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                    <tbody>
                        <tr>
                            <td></td>
                            <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                            <td class="mailbox-name"><b>Camp Name</b></td>
                            <td class="mailbox-subject"><b class="locationTab">Location</b></td>
                            <td class="mailbox-subject"><b>Description</b> </td>
                            <td class="mailbox-attachment"><i class="fa fa-paperclip"></i></td>
                            <td class="mailbox-date"><b>Date</b></td>
                        </tr>
                    </tbody>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td></td>
                                <td class="mailbox-star"><a href="#"><i class="fa fa-star text-yellow"></i></a></td>
                                <!--<td class="mailbox-name"><a href="read-mail.html">Html.DisplayFor(modelItem => item.Name)</a></td>                                -->
                                <td class="mailbox-name"><a href="read-mail.html">@Html.ActionLink(item.Name,"CampPage","Camp",item,null)</a></td>                                
                                <td class="mailbox-subject"><b class="locationTab"> @Html.DisplayFor(modelItem => item.Location)</b></td>
                                <td class="mailbox-subject">@Html.DisplayFor(m => item.Description) </td>
                                <td class="mailbox-attachment"><i class="fa fa-paperclip"></i></td>
                                <td class="mailbox-date">@Html.DisplayFor(m => item.sDate)</td>
                            </tr>
                        }
                    </tbody>

                </table><!-- /.table -->
            </div><!-- /.mail-box-messages -->
        </div><!-- /.box-body -->
        <hr>
    </div><!-- /. box -->
</div><!-- /.col -->


@Scripts.Render("https://code.jquery.com/jquery-3.2.1.js")
@Scripts.Render("~/Scripts/exploreFunc.js")

ProjectDoc/Views/Camp/RegisterPlayer.cshtml
@model ProjectDoc.Models.Camp

@{
    ViewBag.Title = "RegisterPlayer";
}

<h2>RegisterPlayer</h2>